spring:
  datasource:
    url: jdbc:mysql://mysql:3306/MyBackendDB?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: mybackend
    password: password1234
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
